### PR TITLE
Resolves #19 Say which player is looking at which board

### LINKED ISSUE #19: Say which player is looking at which board?

### PR DESCRIPTION
**Pull request by lightvector**
In case you also wanted to review/test before merging. Seemed pretty straightforward.

### CODE REVIEW

**Comment by jonathanpaulson** [comment]
Do you test this? I tested it and it doesn't seem to update the board index. 0-based index seems worse than 1-based index. Not sure if it should be board name or index.

**Comment by jonathanpaulson** [comment]
Ah, you made it work for page up / page down (which I totally forgot existed...) but not the next board / prev board buttons.

**Comment by jonathanpaulson** [comment]
I added a commit making the buttons work and changing the string to be 1-indexed.

**Comment by lightvector** [comment]
Good catches, thanks.

**Pull request merged**
