### PR TITLE
Allow choice of advanced necromancers after board reset

### PR DESCRIPTION
**Pull request by jonathanpaulson**
Tested. Seems like there are probably a lot of edge cases though.

### CODE REVIEW

**Comment by jonathanpaulson** [comment]
It would be nicer IMO to store the list of necroNames on the pieceMod rather than the BoardState, but that makes serializing the pieceMod and ability significantly more annoying.

**Comment by lightvector** [comment]
Do you get your zombie the first turn on the zombie necromancer?

**Comment by lightvector** [comment]
Do you get your extra +2 souls the first turn if you won the previous board on graveyards, and therefore your board resets without you being able to do anything, and you ultimately pick the wealthy necro?

Do you get an extra +2 souls that you shouldn't if you won the previous board on graveyards, and therefore your board resets without you being able to do anything, and of the 3 necros you're given, the first one randomly is the wealthy necro, but you ultimately swap off it to another necro?

And also same question for zombie necro - do you get a zombie that you shouldn't if it's the initial one on the board but you eventually chose another?

**Comment by lightvector** [comment]
Haven't tested, but those are the corner cases I can think of with this particular (definitely "quirky") way of implementing it. Although these seem like tricky issues with almost any implementation.

**Pull request merged**
